### ISSUE TITLE
Wrong reference of node.name

### ISSUE THREAD

**Issue by Yanderuri** [Spico197/bitburner-scripts#1]
```
else if (mode === "hackOne") {
		if (ns.args.length > 1) {
			let startNodeName = ns.args[1]
			if (isHackable(ns, startNodeName)) {
				await hackOne(ns, node.name)
			}
```

I keep running into an error with "node undefined" so I looked at the code.
When you called await hackOne(ns, node.name), node.name should have just been startNodeName under "hackOne" mode

**Comment by Spico197** [comment]
Thank you very much for this. You are right, and the `node.name` should be changed into `startNodeName`. Sorry for the bug, I will fix this issue tomorrow and test the scripts again. Please keep this issue open until the bug has been fixed. Thx again!

**Comment by Spico197** [comment]
Hi, there. I've fixed this bug and other modes have been tested to make the availability.
Thanks and enjoy the game ~
